version: "3"
services:
  web_<project_name>:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "<port>:3000"
    volumes: 
      - ./<project_name>:/opt/app
      - gem_cache_<project_name>:/gems
    env_file: 
      - .env/development/database_<project_name>
      - .env/development/web_<project_name>
    <webpacker_env>
    networks:
      - network_<project_name>
  <webpacker>
  database_<project_name>:
    image: postgres:<postgres_version>
    env_file: 
      - .env/development/database_<project_name>
    volumes: 
      - db_data_<project_name>:/var/lib/postgresql/data
    networks:
      - network_<project_name>
volumes: 
  db_data_<project_name>:
  gem_cache_<project_name>:
networks:
  network_<project_name>:
    ipam:
      driver: default
      config:
        - subnet: "<subnet>/24"